import { Effect, Schema } from "effect"
import { stat as fsStat, readFile } from "node:fs/promises"
import * as path from "node:path"
import { Instance } from "../project/instance"
import { assertExternalDirectoryEffect } from "./external-directory"
import DESCRIPTION from "./lockfile.txt"
import * as Tool from "./tool"

const ACTIONS = ["detect", "list", "find", "info"] as const
type Action = (typeof ACTIONS)[number]

const KINDS = [
  "npm",
  "yarn",
  "yarn-berry",
  "pnpm",
  "bun",
  "cargo",
  "pip",
  "uv",
  "gomod",
  "gemfile",
  "composer",
] as const
type Kind = (typeof KINDS)[number]

const FORMATS = ["lines", "json"] as const
const DEFAULT_LIMIT = 500
const MAX_LIMIT = 5_000
const MAX_BYTES = 64 * 1024 * 1024
const DEP_KINDS = ["prod", "dev", "peer", "optional"] as const
type DepKind = (typeof DEP_KINDS)[number]

export const Parameters = Schema.Struct({
  action: Schema.Literals(ACTIONS).annotate({ description: ACTIONS.join(" | ") }),
  path: Schema.String.check(Schema.isMinLength(1)).annotate({
    description: "Path to the lockfile. Absolute preferred; relative resolves from project dir.",
  }),
  kind: Schema.optional(Schema.Literals(KINDS)).annotate({
    description: "Force a specific parser. Defaults to filename detection.",
  }),
  query: Schema.optional(Schema.String.check(Schema.isMinLength(1))).annotate({
    description: "Exact package name to look up (find).",
  }),
  prefix: Schema.optional(Schema.String).annotate({
    description: "Restrict list results to names starting with this prefix.",
  }),
  dev: Schema.optional(Schema.Boolean).annotate({
    description: "Filter to dev (true) or prod (false) deps. Omit to include all.",
  }),
  direct_only: Schema.optional(Schema.Boolean).annotate({
    description: "list: top-level deps only. Default false.",
  }),
  limit: Schema.optional(
    Schema.Number.check(Schema.isInt(), Schema.isGreaterThanOrEqualTo(1), Schema.isLessThanOrEqualTo(MAX_LIMIT)),
  ).annotate({
    description: `Max entries for list/find. Default ${DEFAULT_LIMIT}.`,
  }),
  format: Schema.optional(Schema.Literals(FORMATS)).annotate({
    description: "Output format: lines (default) or json.",
  }),
})

type Params = Schema.Schema.Type<typeof Parameters>

type Entry = {
  name: string
  version: string
  kind?: DepKind
  scope?: string
  source?: string
  direct?: boolean
}

type Detected = {
  kind: Kind
  lockfile_version?: number | string
}

type Metadata = {
  action: Action
  path: string
  kind?: Kind
  lockfile_version?: number | string
  bytes?: number
  total?: number
  truncated?: boolean
  entries?: Entry[]
  direct?: number
  transitive?: number
  by_kind?: Partial<Record<DepKind, number>>
  total_packages?: number
  sample_names?: string[]
}

const done = (result: Tool.ExecuteResult<Metadata>) => result

// ---------------------------------------------------------------------------
// detection
// ---------------------------------------------------------------------------

const detectKind = (file: string, content: string): Detected => {
  const base = path.basename(file).toLowerCase()
  if (base === "package-lock.json" || base === "npm-shrinkwrap.json") {
    try {
      const j = JSON.parse(content) as { lockfileVersion?: number }
      return { kind: "npm", lockfile_version: j.lockfileVersion }
    } catch {
      return { kind: "npm" }
    }
  }
  if (base === "yarn.lock") {
    if (/__metadata:/.test(content)) return { kind: "yarn-berry" }
    return { kind: "yarn" }
  }
  if (base === "pnpm-lock.yaml" || base === "pnpm-lock.yml") {
    const v = /^lockfileVersion:\s*['"]?([\d.]+)/m.exec(content)?.[1]
    return { kind: "pnpm", lockfile_version: v }
  }
  if (base === "bun.lock") return { kind: "bun" }
  if (base === "cargo.lock") {
    const v = /^version\s*=\s*(\d+)/m.exec(content)?.[1]
    return { kind: "cargo", lockfile_version: v ? Number(v) : undefined }
  }
  if (base === "uv.lock") return { kind: "uv" }
  if (base === "requirements.txt") return { kind: "pip" }
  if (base === "go.sum") return { kind: "gomod" }
  if (base === "gemfile.lock") return { kind: "gemfile" }
  if (base === "composer.lock") return { kind: "composer" }
  // Header-based fallbacks
  if (/^# This file is automatically @generated by Cargo/i.test(content)) return { kind: "cargo" }
  if (/^lockfileVersion:/m.test(content)) return { kind: "pnpm" }
  if (/^# THIS FILE IS GENERATED BY YARN/i.test(content) || /^# yarn lockfile v1/i.test(content))
    return { kind: "yarn" }
  if (/__metadata:\s*\n\s+version: ?\d+/m.test(content)) return { kind: "yarn-berry" }
  if (/^GEM\n/m.test(content) && /^DEPENDENCIES\n/m.test(content)) return { kind: "gemfile" }
  if (/"packages":\s*\[/.test(content) && /"composer":\s*"/.test(content)) return { kind: "composer" }
  if (/^[a-z0-9._-]+==[\d.]+/im.test(content)) return { kind: "pip" }
  if (/^[\w./-]+ v[\d.]+(?:-[\w.]+)?\s+h1:/m.test(content)) return { kind: "gomod" }
  throw new Error("lockfile: cannot detect format from filename or content")
}

// ---------------------------------------------------------------------------
// shared helpers
// ---------------------------------------------------------------------------

const npmScope = (name: string): string | undefined => {
  if (!name.startsWith("@")) return undefined
  const slash = name.indexOf("/")
  return slash > 0 ? name.slice(1, slash) : undefined
}

// ---------------------------------------------------------------------------
// npm package-lock.json
// ---------------------------------------------------------------------------

const parseNpm = (content: string): Entry[] => {
  const json = JSON.parse(content) as {
    lockfileVersion?: number
    dependencies?: Record<string, NpmV1Node>
    packages?: Record<string, NpmV2Node>
  }
  const out: Entry[] = []
  if (json.packages) {
    // v2/v3
    for (const [key, info] of Object.entries(json.packages)) {
      if (key === "") continue
      // key is "node_modules/<name>" or nested "node_modules/x/node_modules/y"
      const segments = key.split("node_modules/").filter(Boolean)
      const name = segments[segments.length - 1]?.replace(/\/$/, "") ?? ""
      if (!name) continue
      out.push({
        name,
        version: info.version ?? "0.0.0",
        kind: info.dev ? "dev" : info.optional ? "optional" : info.peer ? "peer" : "prod",
        scope: npmScope(name),
        source: info.resolved,
        direct: !key.includes("/", "node_modules/".length),
      })
    }
  } else if (json.dependencies) {
    const walk = (deps: Record<string, NpmV1Node>, depth: number) => {
      for (const [name, info] of Object.entries(deps)) {
        out.push({
          name,
          version: info.version ?? "0.0.0",
          kind: info.dev ? "dev" : info.optional ? "optional" : "prod",
          scope: npmScope(name),
          source: info.resolved,
          direct: depth === 0,
        })
        if (info.dependencies) walk(info.dependencies, depth + 1)
      }
    }
    walk(json.dependencies, 0)
  }
  return out
}

interface NpmV1Node {
  version?: string
  dev?: boolean
  optional?: boolean
  resolved?: string
  dependencies?: Record<string, NpmV1Node>
}

interface NpmV2Node {
  version?: string
  dev?: boolean
  optional?: boolean
  peer?: boolean
  resolved?: string
}

// ---------------------------------------------------------------------------
// yarn classic v1
// ---------------------------------------------------------------------------

const parseYarnClassic = (content: string): Entry[] => {
  const lines = content.split(/\r?\n/)
  const out: Entry[] = []
  let i = 0
  while (i < lines.length) {
    const line = lines[i]!
    if (!line || line.startsWith("#") || /^\s/.test(line)) {
      i += 1
      continue
    }
    // Header: "name@spec[, name@spec]:"
    const headerLine = line.replace(/:$/, "").trim()
    if (!headerLine) {
      i += 1
      continue
    }
    let resolved: string | undefined
    let version: string | undefined
    i += 1
    while (i < lines.length && /^\s/.test(lines[i]!)) {
      const sub = lines[i]!.trim()
      const versionMatch = /^version\s+"([^"]+)"/.exec(sub) ?? /^version\s+([\w.+-]+)/.exec(sub)
      if (versionMatch) version = versionMatch[1]
      const resolvedMatch = /^resolved\s+"([^"]+)"/.exec(sub)
      if (resolvedMatch) resolved = resolvedMatch[1]
      i += 1
    }
    const headers = headerLine.split(",").map((s) => s.trim().replace(/^"(.*)"$/, "$1"))
    for (const h of headers) {
      const at = h.startsWith("@") ? h.indexOf("@", 1) : h.indexOf("@")
      const name = at > 0 ? h.slice(0, at) : h
      out.push({
        name,
        version: version ?? "0.0.0",
        scope: npmScope(name),
        source: resolved,
      })
    }
  }
  return dedupeByNameVersion(out)
}

const parseYarnBerry = parseYarnClassic // structurally similar enough for name/version extraction

// ---------------------------------------------------------------------------
// pnpm-lock.yaml
// ---------------------------------------------------------------------------

const parsePnpm = (content: string): Entry[] => {
  const out: Entry[] = []
  const importerSection = /^importers:\s*\n([\s\S]*?)(?=^[a-z][a-zA-Z]+:\s*$)/m.exec(content)
  const directNames = new Set<string>()
  const directKinds = new Map<string, DepKind>()
  if (importerSection) {
    const block = importerSection[1] ?? ""
    const importers = block.split(/^\s*['"]?[^\s][^\n]*?['"]?:\s*\n/m)
    for (const imp of importers) {
      for (const [, kind] of [
        ["dependencies", "prod"],
        ["devDependencies", "dev"],
        ["optionalDependencies", "optional"],
        ["peerDependencies", "peer"],
      ] as Array<[string, DepKind]>) {
        const re = new RegExp(`^\\s+${kind === "prod" ? "dependencies" : kind === "dev" ? "devDependencies" : kind === "optional" ? "optionalDependencies" : "peerDependencies"}:\\s*\\n([\\s\\S]*?)(?=^\\s+[a-zA-Z]+:|\\Z)`, "m")
        const m = re.exec(imp)
        if (!m) continue
        const subblock = m[1] ?? ""
        for (const line of subblock.split(/\r?\n/)) {
          const dep = /^\s{4,}('?([^'\s:]+)'?):/.exec(line)
          if (dep && dep[2]) {
            directNames.add(dep[2])
            if (!directKinds.has(dep[2])) directKinds.set(dep[2], kind as DepKind)
          }
        }
      }
    }
  }

  // packages: section. Pnpm v6+ uses snapshots:; older uses packages:. Either way the package id holds name@version.
  const packagesIndex = content.indexOf("\npackages:")
  if (packagesIndex >= 0) {
    const tail = content.slice(packagesIndex + "\npackages:".length)
    const pkgRe = /^\s+('([^']+)'|"([^"]+)"|([^\s:]+)):\s*$/gm
    let m: RegExpExecArray | null
    while ((m = pkgRe.exec(tail))) {
      const id = m[2] ?? m[3] ?? m[4]
      if (!id) continue
      // pnpm package ids look like /react@18.2.0 or /@types/node@20.0.0(typescript@5.0.0)
      const cleaned = id.replace(/^\//, "")
      const at = cleaned.startsWith("@") ? cleaned.indexOf("@", 1) : cleaned.indexOf("@")
      if (at < 0) continue
      const name = cleaned.slice(0, at)
      let version = cleaned.slice(at + 1)
      version = version.replace(/\(.*\)$/, "")
      out.push({
        name,
        version,
        kind: directKinds.get(name),
        scope: npmScope(name),
        direct: directNames.has(name),
      })
    }
  }
  return dedupeByNameVersion(out)
}

// ---------------------------------------------------------------------------
// bun.lock (text JSON since Bun 1.2)
// ---------------------------------------------------------------------------

const parseBun = (content: string): Entry[] => {
  // bun.lock is a relaxed JSON format. We ignore comments and trailing commas best-effort.
  const cleaned = content
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/^\s*\/\/.*$/gm, "")
    .replace(/,(\s*[}\]])/g, "$1")
  let json: any
  try {
    json = JSON.parse(cleaned)
  } catch {
    return []
  }
  const out: Entry[] = []
  const direct = new Map<string, DepKind>()
  const ws = json?.workspaces?.[""] ?? {}
  for (const [section, kind] of [
    ["dependencies", "prod"],
    ["devDependencies", "dev"],
    ["optionalDependencies", "optional"],
    ["peerDependencies", "peer"],
  ] as Array<[string, DepKind]>) {
    const block = ws[section]
    if (block && typeof block === "object") {
      for (const k of Object.keys(block)) direct.set(k, kind)
    }
  }
  const packages = json?.packages ?? {}
  for (const [id, info] of Object.entries(packages)) {
    if (!Array.isArray(info)) continue
    const locator = info[0]
    if (typeof locator !== "string") continue
    // Locator forms: "name@x.y.z" or "name@x.y.z+sha"
    const at = locator.startsWith("@") ? locator.indexOf("@", 1) : locator.indexOf("@")
    if (at < 0) continue
    const name = locator.slice(0, at)
    const version = locator.slice(at + 1).split("+")[0]!
    out.push({
      name,
      version,
      kind: direct.get(name),
      scope: npmScope(name),
      direct: direct.has(name),
    })
  }
  return dedupeByNameVersion(out)
}

// ---------------------------------------------------------------------------
// Cargo.lock (TOML)
// ---------------------------------------------------------------------------

const parseCargo = (content: string): Entry[] => {
  const out: Entry[] = []
  const blockRe = /\[\[package\]\]\s*([\s\S]*?)(?=\n\[\[|\n\[|$)/g
  let m: RegExpExecArray | null
  while ((m = blockRe.exec(content))) {
    const block = m[1] ?? ""
    const name = /^name\s*=\s*"([^"]+)"/m.exec(block)?.[1]
    const version = /^version\s*=\s*"([^"]+)"/m.exec(block)?.[1]
    const source = /^source\s*=\s*"([^"]+)"/m.exec(block)?.[1]
    if (!name || !version) continue
    out.push({ name, version, source })
  }
  return out
}

// ---------------------------------------------------------------------------
// pip requirements.txt + uv.lock
// ---------------------------------------------------------------------------

const parsePip = (content: string): Entry[] => {
  const out: Entry[] = []
  for (const line of content.split(/\r?\n/)) {
    const t = line.trim()
    if (!t || t.startsWith("#") || t.startsWith("-")) continue
    // name==version or name===version or name~=version are all valid pip pin shapes.
    const m = /^([A-Za-z0-9._\-\[\]]+)\s*(?:==|===|~=)\s*([A-Za-z0-9._+-]+)/.exec(t)
    if (m) out.push({ name: m[1]!.replace(/\[.*\]$/, ""), version: m[2]! })
  }
  return out
}

const parseUv = (content: string): Entry[] => {
  // uv.lock is TOML; we extract [[package]] blocks similarly to Cargo.
  const out: Entry[] = []
  const blockRe = /\[\[package\]\]\s*([\s\S]*?)(?=\n\[\[|\n\[|$)/g
  let m: RegExpExecArray | null
  while ((m = blockRe.exec(content))) {
    const block = m[1] ?? ""
    const name = /^name\s*=\s*"([^"]+)"/m.exec(block)?.[1]
    const version = /^version\s*=\s*"([^"]+)"/m.exec(block)?.[1]
    const source = /^source\s*=\s*\{[^}]*registry\s*=\s*"([^"]+)"/m.exec(block)?.[1]
    if (!name || !version) continue
    out.push({ name, version, source })
  }
  return out
}

// ---------------------------------------------------------------------------
// go.sum
// ---------------------------------------------------------------------------

const parseGoSum = (content: string): Entry[] => {
  const seen = new Set<string>()
  const out: Entry[] = []
  for (const line of content.split(/\r?\n/)) {
    const m = /^(\S+)\s+(v\S+?)(?:\/go\.mod)?\s+h1:/.exec(line)
    if (!m) continue
    const key = `${m[1]}@${m[2]}`
    if (seen.has(key)) continue
    seen.add(key)
    out.push({ name: m[1]!, version: m[2]! })
  }
  return out
}

// ---------------------------------------------------------------------------
// Gemfile.lock
// ---------------------------------------------------------------------------

const parseGemfile = (content: string): Entry[] => {
  const out: Entry[] = []
  const lines = content.split(/\r?\n/)
  const start = lines.findIndex((line) => /^\s*specs:\s*$/.test(line))
  if (start < 0) return out
  for (const line of lines.slice(start + 1)) {
    if (/^\S/.test(line)) break
    const m = /^ {4}([A-Za-z0-9._-]+)\s+\(([^)=][^)]*)\)/.exec(line)
    if (m) out.push({ name: m[1]!, version: m[2]! })
  }
  return out
}

// ---------------------------------------------------------------------------
// composer.lock
// ---------------------------------------------------------------------------

const parseComposer = (content: string): Entry[] => {
  let json: any
  try {
    json = JSON.parse(content)
  } catch {
    return []
  }
  const out: Entry[] = []
  for (const [section, kind] of [
    ["packages", "prod"],
    ["packages-dev", "dev"],
  ] as Array<[string, DepKind]>) {
    const arr = json?.[section]
    if (!Array.isArray(arr)) continue
    for (const p of arr) {
      if (typeof p?.name !== "string" || typeof p?.version !== "string") continue
      out.push({ name: p.name, version: p.version, kind, source: p?.source?.url ?? p?.dist?.url })
    }
  }
  return out
}

// ---------------------------------------------------------------------------
// dispatch
// ---------------------------------------------------------------------------

const dedupeByNameVersion = (entries: Entry[]): Entry[] => {
  const seen = new Set<string>()
  const out: Entry[] = []
  for (const e of entries) {
    const key = `${e.name}@${e.version}@${e.kind ?? ""}`
    if (seen.has(key)) continue
    seen.add(key)
    out.push(e)
  }
  return out
}

const parseByKind = (kind: Kind, content: string): Entry[] => {
  switch (kind) {
    case "npm":
      return parseNpm(content)
    case "yarn":
      return parseYarnClassic(content)
    case "yarn-berry":
      return parseYarnBerry(content)
    case "pnpm":
      return parsePnpm(content)
    case "bun":
      return parseBun(content)
    case "cargo":
      return parseCargo(content)
    case "pip":
      return parsePip(content)
    case "uv":
      return parseUv(content)
    case "gomod":
      return parseGoSum(content)
    case "gemfile":
      return parseGemfile(content)
    case "composer":
      return parseComposer(content)
    default:
      throw new Error(`lockfile: unsupported kind '${kind satisfies never}'`)
  }
}

const filterEntries = (entries: Entry[], params: Params): Entry[] => {
  let out = entries
  if (params.prefix) out = out.filter((e) => e.name.startsWith(params.prefix!))
  if (params.dev === true) out = out.filter((e) => e.kind === "dev" || e.kind === "optional" || e.kind === "peer")
  else if (params.dev === false) out = out.filter((e) => e.kind === "prod" || e.kind === undefined)
  if (params.direct_only) out = out.filter((e) => e.direct === true)
  return out
}

const formatLines = (entries: Entry[]): string =>
  entries.map((e) => `${e.name}@${e.version}${e.kind && e.kind !== "prod" ? ` [${e.kind}]` : ""}`).join("\n")

export const LockfileTool = Tool.define(
  "lockfile",
  Effect.gen(function* () {
    return {
      description: DESCRIPTION,
      parameters: Parameters,
      execute: (params: Params, ctx: Tool.Context<Metadata>) =>
        Effect.gen(function* () {
          const target = path.isAbsolute(params.path) ? params.path : path.join(Instance.worktree, params.path)
          yield* assertExternalDirectoryEffect(ctx, target, { kind: "file" })
          yield* ctx.ask({
            permission: "read",
            patterns: [target],
            always: ["*"],
            metadata: { source: "lockfile", action: params.action, file: target },
          })
          const stat = yield* Effect.promise(() => fsStat(target))
          if (stat.size > MAX_BYTES) {
            throw new Error(`lockfile: refusing to read file larger than ${MAX_BYTES} bytes (got ${stat.size})`)
          }
          const content = yield* Effect.promise(() => readFile(target, "utf8"))
          const detected: Detected = params.kind ? { kind: params.kind } : detectKind(target, content)
          // For detect we already have what we need.
          if (params.action === "detect") {
            const sample = parseByKind(detected.kind, content)
              .slice(0, 8)
              .map((e) => `${e.name}@${e.version}`)
            return done({
              title: `lockfile.detect: ${detected.kind}${detected.lockfile_version ? ` v${detected.lockfile_version}` : ""}`,
              metadata: {
                action: "detect",
                path: target,
                kind: detected.kind,
                lockfile_version: detected.lockfile_version,
                bytes: stat.size,
                sample_names: sample,
              },
              output: [
                `kind: ${detected.kind}`,
                `lockfile_version: ${detected.lockfile_version ?? "(unknown)"}`,
                `bytes: ${stat.size}`,
                `sample: ${sample.length === 0 ? "(none)" : sample.join(", ")}`,
              ].join("\n"),
            })
          }

          const entries = parseByKind(detected.kind, content)
          if (params.action === "info") {
            const direct = entries.filter((e) => e.direct === true).length
            const transitive = entries.length - direct
            const byKind: Partial<Record<DepKind, number>> = {}
            for (const e of entries) {
              if (e.kind) byKind[e.kind] = (byKind[e.kind] ?? 0) + 1
            }
            return done({
              title: `lockfile.info: ${entries.length} packages (${detected.kind})`,
              metadata: {
                action: "info",
                path: target,
                kind: detected.kind,
                lockfile_version: detected.lockfile_version,
                bytes: stat.size,
                total_packages: entries.length,
                direct,
                transitive,
                by_kind: byKind,
              },
              output: [
                `path:        ${target}`,
                `kind:        ${detected.kind}`,
                `version:     ${detected.lockfile_version ?? "(unknown)"}`,
                `bytes:       ${stat.size}`,
                `total:       ${entries.length}`,
                `direct:      ${direct}`,
                `transitive:  ${transitive}`,
                `by_kind:     ${
                  Object.entries(byKind)
                    .map(([k, v]) => `${k}=${v}`)
                    .join(", ") || "(none)"
                }`,
              ].join("\n"),
            })
          }

          if (params.action === "find") {
            if (!params.query) throw new Error("lockfile: 'query' is required for find")
            const matches = entries.filter((e) => e.name === params.query)
            const limit = params.limit ?? DEFAULT_LIMIT
            const truncated = matches.length > limit
            const slice = matches.slice(0, limit)
            return done({
              title: `lockfile.find ${params.query}: ${matches.length}`,
              metadata: {
                action: "find",
                path: target,
                kind: detected.kind,
                bytes: stat.size,
                total: matches.length,
                truncated,
                entries: slice,
              },
              output: params.format === "json" ? JSON.stringify(slice, null, 2) : formatLines(slice),
            })
          }

          // list
          const filtered = filterEntries(entries, params)
          const limit = params.limit ?? DEFAULT_LIMIT
          const truncated = filtered.length > limit
          const slice = filtered.slice(0, limit)
          return done({
            title: `lockfile.list: ${slice.length}${truncated ? ` of ${filtered.length}` : ""} (${detected.kind})`,
            metadata: {
              action: "list",
              path: target,
              kind: detected.kind,
              lockfile_version: detected.lockfile_version,
              bytes: stat.size,
              total: filtered.length,
              truncated,
              entries: slice,
            },
            output: params.format === "json" ? JSON.stringify(slice, null, 2) : formatLines(slice),
          })
        }),
    }
  }),
)

export const __testing = {
  detectKind,
  parseNpm,
  parseYarnClassic,
  parsePnpm,
  parseBun,
  parseCargo,
  parsePip,
  parseUv,
  parseGoSum,
  parseGemfile,
  parseComposer,
  filterEntries,
  formatLines,
}
