import { describe, expect } from "bun:test"
import { Effect, Exit, Layer } from "effect"
import { writeFile } from "node:fs/promises"
import * as path from "node:path"
import { CrossSpawnSpawner } from "@opencode-ai/core/cross-spawn-spawner"
import { AppFileSystem } from "@opencode-ai/core/filesystem"
import { Agent } from "../../src/agent/agent"
import { MessageID, SessionID } from "../../src/session/schema"
import { Tool } from "../../src/tool"
import { LockfileTool, __testing } from "../../src/tool/lockfile"
import { Truncate } from "../../src/tool"
import { provideTmpdirInstance } from "../fixture/fixture"
import { testEffect } from "../lib/effect"

const it = testEffect(
  Layer.mergeAll(CrossSpawnSpawner.defaultLayer, AppFileSystem.defaultLayer, Truncate.defaultLayer, Agent.defaultLayer),
)

const baseCtx: Tool.Context = {
  sessionID: SessionID.make("ses_test"),
  messageID: MessageID.make(""),
  callID: "",
  agent: "build",
  abort: AbortSignal.any([]),
  messages: [],
  metadata: () => Effect.void,
  ask: () => Effect.void,
}

describe("tool.lockfile parsers", () => {
  it.live("npm v3 lockfile produces direct + transitive deps", () =>
    Effect.gen(function* () {
      const json = JSON.stringify({
        name: "demo",
        lockfileVersion: 3,
        packages: {
          "": { name: "demo", version: "1.0.0" },
          "node_modules/react": { version: "18.2.0", resolved: "https://registry.npmjs.org/react/-/react-18.2.0.tgz" },
          "node_modules/react/node_modules/loose-envify": { version: "1.4.0", dev: false },
          "node_modules/typescript": { version: "5.4.0", dev: true },
        },
      })
      const entries = __testing.parseNpm(json)
      const react = entries.find((e) => e.name === "react")
      const ts = entries.find((e) => e.name === "typescript")
      const lo = entries.find((e) => e.name === "loose-envify")
      expect(react?.version).toBe("18.2.0")
      expect(react?.direct).toBe(true)
      expect(ts?.kind).toBe("dev")
      expect(lo?.direct).toBe(false)
    }),
  )

  it.live("yarn classic lockfile parses headers and versions", () =>
    Effect.gen(function* () {
      const txt = [
        "# yarn lockfile v1",
        "",
        'react@^18.2.0:',
        '  version "18.2.0"',
        '  resolved "https://registry.yarnpkg.com/react/-/react-18.2.0.tgz"',
        "",
        '"@types/node@*", "@types/node@^20.0.0":',
        '  version "20.10.0"',
        "",
      ].join("\n")
      const entries = __testing.parseYarnClassic(txt)
      const names = entries.map((e) => `${e.name}@${e.version}`)
      expect(names).toContain("react@18.2.0")
      expect(names).toContain("@types/node@20.10.0")
    }),
  )

  it.live("Cargo.lock extracts package name + version", () =>
    Effect.gen(function* () {
      const txt = [
        "# This file is automatically @generated by Cargo.",
        "version = 3",
        "",
        "[[package]]",
        'name = "serde"',
        'version = "1.0.197"',
        'source = "registry+https://github.com/rust-lang/crates.io-index"',
        "",
        "[[package]]",
        'name = "tokio"',
        'version = "1.36.0"',
        "",
      ].join("\n")
      const entries = __testing.parseCargo(txt)
      expect(entries.map((e) => `${e.name}@${e.version}`)).toEqual(["serde@1.0.197", "tokio@1.36.0"])
    }),
  )

  it.live("pip requirements parses == pins and ignores comments", () =>
    Effect.gen(function* () {
      const txt = [
        "# top",
        "Django==5.0.1",
        "requests==2.31.0  # via something",
        "-e git+https://example.com/foo.git#egg=foo",
        "numpy~=1.26.0",
        "ipython===8.20.0",
      ].join("\n")
      const entries = __testing.parsePip(txt)
      const got = entries.map((e) => `${e.name}@${e.version}`)
      expect(got).toContain("Django@5.0.1")
      expect(got).toContain("requests@2.31.0")
      expect(got).toContain("numpy@1.26.0")
      expect(got).toContain("ipython@8.20.0")
    }),
  )

  it.live("go.sum dedupes go.mod hash entries", () =>
    Effect.gen(function* () {
      const txt = [
        "github.com/foo/bar v1.2.3 h1:aaaa",
        "github.com/foo/bar v1.2.3/go.mod h1:bbbb",
        "github.com/baz/qux v0.4.5 h1:cccc",
      ].join("\n")
      const entries = __testing.parseGoSum(txt)
      expect(entries.map((e) => `${e.name}@${e.version}`).sort()).toEqual([
        "github.com/baz/qux@v0.4.5",
        "github.com/foo/bar@v1.2.3",
      ])
    }),
  )

  it.live("Gemfile.lock parses gem specs", () =>
    Effect.gen(function* () {
      const txt = [
        "GEM",
        "  remote: https://rubygems.org/",
        "  specs:",
        "    rails (7.1.3)",
        "      activerecord (= 7.1.3)",
        "    activerecord (7.1.3)",
        "",
        "PLATFORMS",
        "  ruby",
        "",
        "DEPENDENCIES",
        "  rails",
      ].join("\n")
      const entries = __testing.parseGemfile(txt)
      expect(entries.map((e) => `${e.name}@${e.version}`)).toEqual(["rails@7.1.3", "activerecord@7.1.3"])
    }),
  )

  it.live("composer.lock parses prod and dev sections", () =>
    Effect.gen(function* () {
      const json = JSON.stringify({
        packages: [{ name: "monolog/monolog", version: "3.5.0" }],
        "packages-dev": [{ name: "phpunit/phpunit", version: "10.5.0" }],
      })
      const entries = __testing.parseComposer(json)
      expect(entries).toEqual([
        { name: "monolog/monolog", version: "3.5.0", kind: "prod", source: undefined },
        { name: "phpunit/phpunit", version: "10.5.0", kind: "dev", source: undefined },
      ])
    }),
  )

  it.live("detectKind picks the right parser by filename", () =>
    Effect.gen(function* () {
      expect(__testing.detectKind("/x/package-lock.json", "{}").kind).toBe("npm")
      expect(__testing.detectKind("/x/yarn.lock", "# yarn lockfile v1").kind).toBe("yarn")
      expect(__testing.detectKind("/x/yarn.lock", "__metadata:\n  version: 6").kind).toBe("yarn-berry")
      expect(__testing.detectKind("/x/Cargo.lock", "# This file is automatically @generated by Cargo").kind).toBe(
        "cargo",
      )
      expect(__testing.detectKind("/x/pnpm-lock.yaml", "lockfileVersion: '6.0'").kind).toBe("pnpm")
    }),
  )

  it.live("filterEntries respects prefix + dev + direct_only", () =>
    Effect.gen(function* () {
      const entries = [
        { name: "react", version: "18.0.0", kind: "prod" as const, direct: true },
        { name: "react-dom", version: "18.0.0", kind: "prod" as const, direct: false },
        { name: "vitest", version: "1.0.0", kind: "dev" as const, direct: true },
      ]
      const onlyDirect = __testing.filterEntries(entries, {
        action: "list",
        path: "x",
        direct_only: true,
      } as any)
      expect(onlyDirect.map((e) => e.name)).toEqual(["react", "vitest"])
      const prod = __testing.filterEntries(entries, { action: "list", path: "x", dev: false } as any)
      expect(prod.map((e) => e.name)).toEqual(["react", "react-dom"])
      const prefixed = __testing.filterEntries(entries, {
        action: "list",
        path: "x",
        prefix: "react",
      } as any)
      expect(prefixed.map((e) => e.name)).toEqual(["react", "react-dom"])
    }),
  )
})

describe("tool.lockfile tool", () => {
  it.live("asks read permission before reading the lockfile", () =>
    provideTmpdirInstance((dir) =>
      Effect.gen(function* () {
        const file = path.join(dir, "package-lock.json")
        yield* Effect.promise(() => writeFile(file, "{}", "utf8"))

        const calls: Array<Parameters<Tool.Context["ask"]>[0]> = []
        const toolInfo = yield* LockfileTool
        const tool = yield* toolInfo.init()
        const exit = yield* Effect.exit(
          tool.execute(
            { action: "detect", path: file },
            {
              ...baseCtx,
              ask: (input) =>
                Effect.sync(() => {
                  calls.push(input)
                  throw new Error("permission probe")
                }),
            },
          ),
        )
        expect(Exit.isFailure(exit)).toBe(true)
        expect(calls).toHaveLength(1)
        expect(calls[0]!.permission).toBe("read")
      }),
    ),
  )

  it.live("detects npm lockfile by content", () =>
    provideTmpdirInstance((dir) =>
      Effect.gen(function* () {
        const file = path.join(dir, "package-lock.json")
        yield* Effect.promise(() =>
          writeFile(
            file,
            JSON.stringify({
              name: "x",
              lockfileVersion: 3,
              packages: { "": { name: "x", version: "1.0.0" } },
            }),
            "utf8",
          ),
        )

        const toolInfo = yield* LockfileTool
        const tool = yield* toolInfo.init()
        const result = yield* tool.execute({ action: "detect", path: file }, baseCtx)
        expect(result.metadata.kind).toBe("npm")
        expect(result.metadata.lockfile_version).toBe(3)
      }),
    ),
  )

  it.live("info reports counts on a tiny Cargo.lock", () =>
    provideTmpdirInstance((dir) =>
      Effect.gen(function* () {
        const file = path.join(dir, "Cargo.lock")
        yield* Effect.promise(() =>
          writeFile(
            file,
            [
              "# This file is automatically @generated by Cargo.",
              "version = 3",
              "",
              "[[package]]",
              'name = "serde"',
              'version = "1.0.197"',
              "",
              "[[package]]",
              'name = "tokio"',
              'version = "1.36.0"',
              "",
            ].join("\n"),
            "utf8",
          ),
        )

        const toolInfo = yield* LockfileTool
        const tool = yield* toolInfo.init()
        const result = yield* tool.execute({ action: "info", path: file }, baseCtx)
        expect(result.metadata.kind).toBe("cargo")
        expect(result.metadata.total_packages).toBe(2)
      }),
    ),
  )
})
